### ISSUE TITLE
How to convert arabic timestamp to digit?

### ISSUE THREAD

**Issue by webserveis** [YektaDev/AnyNum#1]

**Comment by YektaDev** [comment]
I did not understand your question fully but, if the timestamp is stored as an integer (or double), and should be converted into an string containing Arabic digits, you might want to use: `yourIntegerTimestampVar.toArString()`.
If the timestamp is stored as a string containing Arabic digits, you may consider using `yourArabicStringVar.numArToEn()`.

**Comment by webserveis** [comment]
Sorry I did not answer more precisely, I read lines with the following structure the timestamp is in text and to parse it to a data object I need to convert to English numbering
I have read lines with timestamp `٢٣‏/٨‏/٢٠١٧ ٢٣:٣٢ - الاستماع إليها. انقر هنا لمعرفة المزيد.`

**Comment by YektaDev** [comment]
No worries.
Using `String.numArToEn()` on your example will return: `23‏/8‏/2017 23:32 - الاستماع إليها. انقر هنا لمعرفة المزيد.`
